import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'aboutPage',
  title: 'About Page',
  type: 'document',
  // Singleton: only one "About Page" document should ever exist.
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'local', title: 'Local Church' },
    { name: 'conference', title: 'Conference' },
    { name: 'worldwide', title: 'Worldwide Church' },
    { name: 'stats', title: 'Worldwide Stats' },
    { name: 'globalFamily', title: 'Global Family' },
    { name: 'beliefs', title: 'Beliefs CTA' },
  ],
  fields: [
    defineField({
      name: 'heroHeadline',
      title: 'Headline',
      description: 'e.g. "A Local Church. A Regional Family. A Worldwide Movement."',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroSubheadline',
      title: 'Subheadline',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'heroTagline',
      title: 'Tagline',
      description: 'e.g. "Local → Regional → Worldwide"',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'scrollVisual',
      title: 'Local / Regional / Worldwide Graphic',
      description:
        'The tall infographic showing Athens → Georgia-Cumberland Conference → worldwide church. Stays pinned on screen while the Local, Conference, and Worldwide sections below scroll past, with the matching part of the graphic highlighted.',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),

    defineField({
      name: 'localIntroHeading',
      title: 'Intro Heading',
      description: 'e.g. "It starts here."',
      type: 'string',
      group: 'local',
    }),
    defineField({
      name: 'localIntroBody',
      title: 'Intro Body',
      type: 'text',
      rows: 3,
      group: 'local',
    }),
    defineField({
      name: 'pastorHeading',
      title: 'Pastor Section Heading',
      description: 'e.g. "Meet Our Pastor"',
      type: 'string',
      group: 'local',
    }),
    defineField({
      name: 'pastorName',
      title: 'Pastor Name',
      type: 'string',
      group: 'local',
    }),
    defineField({
      name: 'pastorPhoto',
      title: 'Pastor Photo',
      type: 'image',
      options: { hotspot: true },
      group: 'local',
    }),
    defineField({
      name: 'pastorBio',
      title: 'Pastor Bio (paragraphs)',
      type: 'array',
      of: [{ type: 'text', rows: 3 }],
      group: 'local',
    }),
    defineField({
      name: 'pullQuote',
      title: 'Pull Quote',
      type: 'text',
      rows: 2,
      group: 'local',
    }),
    defineField({
      name: 'localCtaHeading',
      title: 'CTA Heading',
      description: 'e.g. "Want to get to know us?"',
      type: 'string',
      group: 'local',
    }),
    defineField({
      name: 'localCtaBody',
      title: 'CTA Body',
      type: 'text',
      rows: 2,
      group: 'local',
    }),
    defineField({
      name: 'localCtaButtonLabel',
      title: 'CTA Button Label',
      description: 'e.g. "Plan Your Visit"',
      type: 'string',
      group: 'local',
    }),
    defineField({
      name: 'localCtaButtonLink',
      title: 'CTA Button Link',
      description: 'Internal route path, e.g. /im-new',
      type: 'string',
      group: 'local',
    }),

    defineField({
      name: 'conferenceHeadline',
      title: 'Headline',
      description: 'e.g. "Connected Across Georgia & Tennessee"',
      type: 'string',
      group: 'conference',
    }),
    defineField({
      name: 'conferenceIntro',
      title: 'Intro',
      type: 'text',
      rows: 4,
      group: 'conference',
    }),
    defineField({
      name: 'conferenceChurchCount',
      title: 'Church Count',
      description: 'e.g. "186 Churches"',
      type: 'string',
      group: 'conference',
    }),
    defineField({
      name: 'conferenceMemberCount',
      title: 'Member Count',
      description: 'e.g. "48,482 Members"',
      type: 'string',
      group: 'conference',
    }),
    defineField({
      name: 'missionHeading',
      title: 'Mission Heading',
      description: 'e.g. "Growing Disciples Together"',
      type: 'string',
      group: 'conference',
    }),
    defineField({
      name: 'missionBody',
      title: 'Mission Body',
      type: 'text',
      rows: 4,
      group: 'conference',
    }),
    defineField({
      name: 'leadershipHeading',
      title: 'Leadership Heading',
      description: 'e.g. "Meet the Conference"',
      type: 'string',
      group: 'conference',
    }),
    defineField({
      name: 'leaders',
      title: 'Leaders',
      type: 'array',
      of: [{ type: 'leaderCard' }],
      group: 'conference',
    }),
    defineField({
      name: 'conferenceCtaLabel',
      title: 'CTA Button Label',
      description: 'e.g. "Visit Georgia-Cumberland Conference"',
      type: 'string',
      group: 'conference',
    }),
    defineField({
      name: 'conferenceCtaLink',
      title: 'CTA Button Link',
      type: 'url',
      group: 'conference',
    }),

    defineField({
      name: 'worldwideTransition',
      title: 'Transition Line',
      description: 'e.g. "But our story doesn\'t end here."',
      type: 'string',
      group: 'worldwide',
    }),
    defineField({
      name: 'worldwideHeadline',
      title: 'Headline',
      description: 'e.g. "A Church Without Borders"',
      type: 'string',
      group: 'worldwide',
    }),
    defineField({
      name: 'worldwideIntro',
      title: 'Intro',
      type: 'text',
      rows: 4,
      group: 'worldwide',
    }),
    defineField({
      name: 'angels',
      title: "Three Angels' Messages Cards",
      type: 'array',
      of: [{ type: 'angelCard' }],
      validation: (Rule) => Rule.max(3),
      group: 'worldwide',
    }),
    defineField({
      name: 'connectingStatement',
      title: 'Connecting Statement',
      description:
        'e.g. "These messages are not simply doctrines we believe. They are a calling we live."',
      type: 'text',
      rows: 2,
      group: 'worldwide',
    }),
    defineField({
      name: 'connectingBody',
      title: 'Connecting Body',
      type: 'text',
      rows: 3,
      group: 'worldwide',
    }),

    defineField({
      name: 'statsHeading',
      title: 'Heading (optional)',
      type: 'string',
      group: 'stats',
    }),
    defineField({
      name: 'stats',
      title: 'Stats',
      description: 'Keep this to six numbers or fewer.',
      type: 'array',
      of: [{ type: 'statItem' }],
      validation: (Rule) => Rule.max(6),
      group: 'stats',
    }),

    defineField({
      name: 'globalFamilyHeading',
      title: 'Heading',
      description: 'e.g. "One Church. Many Places. One Hope."',
      type: 'string',
      group: 'globalFamily',
    }),
    defineField({
      name: 'globalFamilyParagraphs',
      title: 'Paragraphs',
      type: 'array',
      of: [{ type: 'text', rows: 3 }],
      group: 'globalFamily',
    }),

    defineField({
      name: 'beliefsHeading',
      title: 'Heading',
      description: 'e.g. "Want to Know What We Believe?"',
      type: 'string',
      group: 'beliefs',
    }),
    defineField({
      name: 'beliefsBody',
      title: 'Body',
      type: 'text',
      rows: 3,
      group: 'beliefs',
    }),
    defineField({
      name: 'beliefsCardHeading',
      title: 'Card Heading',
      description: 'e.g. "28 Fundamental Beliefs"',
      type: 'string',
      group: 'beliefs',
    }),
    defineField({
      name: 'beliefsCardBody',
      title: 'Card Body',
      type: 'text',
      rows: 3,
      group: 'beliefs',
    }),
    defineField({
      name: 'beliefsButtonLabel',
      title: 'Button Label',
      description: 'e.g. "Explore Our Fundamental Beliefs"',
      type: 'string',
      group: 'beliefs',
    }),
    defineField({
      name: 'beliefsButtonLink',
      title: 'Button Link',
      type: 'url',
      group: 'beliefs',
    }),
  ],
  preview: {
    prepare() {
      return { title: 'About Page' }
    },
  },
})
